### ISSUE TITLE
mimalloc build error

### ISSUE THREAD

**Issue by stytim** [catid/xrcap#1]
Hi Chris, first of all, amazing project! I was trying to build your project and the mimalloc build error occurs: 
E:\xrcap-master\extern\src\mimalloc\src\os.c(91): error C2143: syntax error: missing ')' before '*' [E:\xrcap-master\extern\build\mimalloc-prefix\src\mimalloc-build\mimalloc.vcxproj] [E:\xrcap-master\extern\build\mimalloc.vcxproj]

E:\xrcap-master\extern\src\mimalloc\src\os.c(91): error C2081: 'MEM_EXTENDED_PARAMETER': name in formal parameter list illegal [E:\xrcap-master\extern\build\mimalloc-prefix\src\mimalloc-build\mimalloc.vcxproj] [E:\xrcap-master\extern\build\mimalloc.vcxproj
]

E:\xrcap-master\extern\src\mimalloc\src\os.c(91): error C2143: syntax error: missing '{' before '*' [E:\xrcap-master\extern\build\mimalloc-prefix\src\mimalloc-build\mimalloc.vcxproj] [E:\xrcap-master\extern\build\mimalloc.vcxproj]

E:\xrcap-master\extern\src\mimalloc\src\os.c(91): error C2059: syntax error: ',' [E:\xrcap-master\extern\build\mimalloc-prefix\src\mimalloc-build\mimalloc.vcxproj] [E:\xrcap-master\extern\build\mimalloc.vcxproj]
...

I tried to change mimalloc version to other like 1.0.8, 1.10, 1.2 etc. and they all gave me different errors. I was using CMake 3.15.4, Visual Studio 2017 x64.

**Comment by catid** [comment]
VS2019 should work.  Is it not feasible to update?

**Comment by stytim** [comment]
Thanks, I will try with VS2019.

**Comment by stytim** [comment]
Hi Chris,

The issue remains even after switching to VS2019. Here are my steps: 

1. Launch CMake GUI
2. Select where is source code and where to build binaries.
3. Click Configure.
4. Choose Visual Studio 16 2019 as generator.

Can you help me with this issue?

Thanks

**Comment by catid** [comment]
I'll try to reproduce the issue after work today

**Comment by catid** [comment]
I wasn't able to reproduce the problem when using CMake GUI to perform the build.  Updated Readme to include more familiar Cmake build instructions as you described above.

Reading through `os.c` I see that the error is probably at `MEM_EXTENDED_PARAMETER`.  I'm doing my builds on a Windows 10 computer with the Windows Kit installed.  Perhaps that's required also?

https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk

**Comment by stytim** [comment]
Thanks for the reply. I am able to build it on a different PC that has Windows SDK 10.0.18362.1 and 10.0.17763.132 installed.
